compressionLevel: mixed

enableGlobalCache: true

yarnPath: .yarn/releases/yarn-4.0.0-rc.50.cjs


injectEnvironmentFiles:
  - .env?

npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmAuthToken: "${FONTAWESOME_NPM_AUTH_TOKEN}"
    npmRegistryServer: "https://npm.fontawesome.com/"
